---
# tasks file for roles/webservers

- name: Copy all resource files from loacvl to webservers
  copy:
    src: ../files/index.php
    dest: "{{ path_to_app }}"
    mode: 0755

- name: create simple info page
  copy:
    dest: "{{ path_to_app }}/info.php"
    content: "<h1> Information abput our webserver is : {{ ansible_hostname }} </h1>"

- name: List directory contents
  become: true
  command: ls -la {{ path_to_app }}
  register: dir_contents

- name: Debug directory contents
  debug:
    msg: "{{ dir_contents }}"

- name: Condigfure the php ini file
  lineinfile:
    path: /etc/php.ini
    regexp: ^short_open_tag
    line: 'short_open_tag=On'
  notify: restart apache