# install-services.yml

---

  - hosts: loadbalancers
    become: true
    tasks:
      - name: install apache services on loadbalancer
        yum:
          name: httpd
          state: present
      - name: start the apache service on laod balancer
        service:
          name: httpd
          state: started
          enabled: yes


  - hosts: webservers
    become: true
    tasks:
      - name: installing apache services and php service on webservers
        yum:
          name:
            - httpd
            - php
          state: present
      - name: ensure apache startes on webservers
        service: name=httpd state=started enabled=yes


