# setup-app.yml

---

  - hosts: webservers
    become: true

    vars:
      path_to_app: "/var/www/html"

    vars_prompt:
      - name: "upload_var_index"
        prompt: "Do you want to upload index.php?"

      - name: "create_var_info"
        prompt: "Do you want to create info.php?"



    tasks:
      - name: Copy all resource files from loacvl to webservers
        copy:
          src: ../index.php
          dest: "{{ path_to_app }}"
          mode: 0755
        when: upload_var_index == 'yes'
        tags: upload

      - name: create simple info page
        copy:
          dest: "{{ path_to_app }}/info.php"
          content: "<h1> Information abput our webserver is : {{ ansible_hostname }}. These are changes. </h1>"
        when: create_var_info == 'yes'
        tags: create

      - name: List directory contents
        become: true
        command: ls -la {{ path_to_app }}
        register: dir_contents

      - name: Debug directory contents
        debug:
          msg: "{{ dir_contents }}"

      - name: Condigfure the php ini file
        lineinfile:
          path: /etc/php.ini
          regexp: ^short_open_tag
          line: 'short_open_tag=On'
        notify: restart apache

    handlers:
      - name: restart apache
        service:
          name: httpd
          state: restarted
