---
# tasks file for roles/loadbalancers

- name: creating the template for load balancer
  template:
    src: ../templates/lb-config.j2
    dest: /etc/httpd/conf.d/lb.conf
    group: wheel
    owner: bin
    mode: 064
  notify: restart apache